export const ARTICLE_LIST_REQUEST = "ARTICLE_LIST_REQUEST";
export const ARTICLE_LIST_SUCCESS = "ARTICLE_LIST_SUCCESS";
export const ARTICLE_LIST_FAIL = "ARTICLE_LIST_FAIL";
export const ARTICLE_REQUEST = "ARTICLE_REQUEST";


export const ARTICLE_SUCCESS = "ARTICLE_SUCCESS";

export const ARTICLE_CREATE_REQUEST = "ARTICLE_CREATE_REQUEST";
export const ARTICLE_CREATE_SUCCESS = "ARTICLE_CREATE_SUCCESS";
export const ARTICLE_CREATE_FAIL = "ARTICLE_CREATE_FAIL";

export const ARTICLE_UPDATE_REQUEST = "ARTICLE_UPDATE_REQUEST";
export const ARTICLE_UPDATE_SUCCESS = "ARTICLE_UPDATE_SUCCESS";
export const ARTICLE_UPDATE_FAIL = "ARTICLE_UPDATE_FAIL";

export const ARTICLE_DELETE_REQUEST = "ARTICLE_DELETE_REQUEST";
export const ARTICLE_DELETE_SUCCESS = "ARTICLE_DELETE_SUCCESS";
export const ARTICLE_DELETE_FAIL = "ARTICLE_DELETE_FAIL";

export const ARTICLE_APPROVE_REQUEST = "ARTICLE_APPROVE_REQUEST";
export const ARTICLE_APPROVE_SUCCESS = "ARTICLE_APPROVE_SUCCESS";
export const ARTICLE_APPROVE_FAIL = "ARTICLE_APPROVE_FAIL";

export const ARTICLE_DENY_REQUEST = "ARTICLE_DENY_REQUEST";
export const ARTICLE_DENY_SUCCESS = "ARTICLE_DENY_SUCCESS";
export const ARTICLE_DENY_FAIL = "ARTICLE_DENY_FAIL";

export const SET_APPROVED_DATA = "SET_APPROVED_DATA";
