export const DONATELABOR_LIST_REQUEST = "DONATELABOR_LIST_REQUEST";
export const DONATELABOR_LIST_SUCCESS = "DONATELABOR_LIST_SUCCESS";
export const DONATELABOR_LIST_FAIL = "DONATELABOR_LIST_FAIL";

export const DONATELABOR_CREATE_REQUEST = "DONATELABOR_CREATE_REQUEST";
export const DONATELABOR_CREATE_SUCCESS = "DONATELABOR_CREATE_SUCCESS";
export const DONATELABOR_CREATE_FAIL = "DONATELABOR_CREATE_FAIL";

export const DONATELABOR_UPDATE_REQUEST = "DONATELABOR_UPDATE_REQUEST";
export const DONATELABOR_UPDATE_SUCCESS = "DONATELABOR_UPDATE_SUCCESS";
export const DONATELABOR_UPDATE_FAIL = "DONATELABOR_UPDATE_FAIL";

export const DONATELABOR_DELETE_REQUEST = "DONATELABOR_DELETE_REQUEST";
export const DONATELABOR_DELETE_SUCCESS = "DONATELABOR_DELETE_SUCCESS";
export const DONATELABOR_DELETE_FAIL = "DONATELABOR_DELETE_FAIL";

export const DONATEPAYMENT_LIST_REQUEST = "DONATEPAYMENT_LIST_REQUEST";
export const DONATEPAYMENT_LIST_SUCCESS = "DONATEPAYMENT_LIST_SUCCESS";
export const DONATEPAYMENT_LIST_FAIL = "DONATEPAYMENT_LIST_FAIL";

export const DONATEPAYMENT_CREATE_REQUEST = "DONATEPAYMENT_CREATE_REQUEST";
export const DONATEPAYMENT_CREATE_SUCCESS = "DONATEPAYMENT_CREATE_SUCCESS";
export const DONATEPAYMENT_CREATE_FAIL = "DONATEPAYMENT_CREATE_FAIL";
