export const INNOVATION_LIST_REQUEST = "INNOVATION_LIST_REQUEST";
export const INNOVATION_LIST_SUCCESS = "INNOVATION_LIST_SUCCESS";
export const INNOVATION_LIST_FAIL = "INNOVATION_LIST_FAIL";
export const INNOVATION_REQUEST = "INNOVATION_REQUEST";

export const INNOVAIONONE_SUCCESS = "INNOVAIONONE_SUCCESS";

export const INNOVATION_CREATE_REQUEST = "INNOVATION_CREATE_REQUEST";
export const INNOVATION_CREATE_SUCCESS = "INNOVATION_CREATE_SUCCESS";
export const INNOVATION_CREATE_FAIL = "INNOVATION_CREATE_FAIL";

export const INNOVATION_UPDATE_REQUEST = "INNOVATION_UPDATE_REQUEST";
export const INNOVATION_UPDATE_SUCCESS = "INNOVATION_UPDATE_SUCCESS";
export const INNOVATION_UPDATE_FAIL = "INNOVATION_UPDATE_FAIL";

export const INNOVATION_DELETE_REQUEST = "INNOVATION_DELETE_REQUEST";
export const INNOVATION_DELETE_SUCCESS = "INNOVATION_DELETE_SUCCESS";
export const INNOVATION_DELETE_FAIL = "INNOVATION_DELETE_FAIL";

export const INNOVATION_APPROVE_REQUEST = "INNOVATION_APPROVE_REQUEST";
export const INNOVATION_APPROVE_SUCCESS = "INNOVATION_APPROVE_SUCCESS";
export const INNOVATION_APPROVE_FAIL = "INNOVATION_APPROVE_FAIL";

export const INNOVATION_DENY_REQUEST = "INNOVATION_DENY_REQUEST";
export const INNOVATION_DENY_SUCCESS = "INNOVATION_DENY_SUCCESS";
export const INNOVATION_DENY_FAIL = "INNOVATION_DENY_FAIL";

export const SET_APPROVED_DATA = "SET_APPROVED_DATA";



