export const INNOVATION_LIST_REQUEST = "INNOVATION_LIST_REQUEST";
export const INNOVATION_LIST_SUCCESS = "INNOVATION_LIST_SUCCESS";
export const INNOVATION_LIST_FAIL = "INNOVATION_LIST_FAIL";
export const INNOVATION_REQUEST = "INNOVATION_REQUEST";
export const INNOVAIONONE_SUCCESS = "INNOVAIONONE_SUCCESS";

