export const QUALITY_LIST_REQUEST = "QUALITY_LIST_REQUEST";
export const QUALITY_LIST_SUCCESS = "QUALITY_LIST_SUCCESS";
export const QUALITY_LIST_FAIL = "QUALITY_LIST_FAIL";
export const QUALITY_REQUEST = "QUALITY_REQUEST";

export const QUALITYONE_SUCCESS = "QUALITYONE_SUCCESS";

export const QUALITY_CREATE_REQUEST = "QUALITY_CREATE_REQUEST";
export const QUALITY_CREATE_SUCCESS = "QUALITY_CREATE_SUCCESS";
export const QUALITY_CREATE_FAIL = "QUALITY_CREATE_FAIL";

export const QUALITY_UPDATE_REQUEST = "QUALITY_UPDATE_REQUEST";
export const QUALITY_UPDATE_SUCCESS = "QUALITY_UPDATE_SUCCESS";
export const QUALITY_UPDATE_FAIL = "QUALITY_UPDATE_FAIL";

export const QUALITY_DELETE_REQUEST = "QUALITY_DELETE_REQUEST";
export const QUALITY_DELETE_SUCCESS = "QUALITY_DELETE_SUCCESS";
export const QUALITY_DELETE_FAIL = "QUALITY_DELETE_FAIL";
