export const INNOVATIONSUPPORT_LIST_REQUEST = "INNOVATIONSUPPORT_LIST_REQUEST";
export const INNOVATIONSUPPORT_LIST_SUCCESS = "INNOVATIONSUPPORT_LIST_SUCCESS";
export const INNOVATIONSUPPORT_LIST_FAIL = "INNOVATIONSUPPORT_LIST_FAIL";
export const INNOVATIONSUPPORT_REQUEST = "INNOVATIONSUPPORT_REQUEST";

export const INNOVATIONSUPPORT_CREATE_REQUEST = "INNOVATIONSUPPORT_CREATE_REQUEST";
export const INNOVATIONSUPPORT_CREATE_SUCCESS = "INNOVATIONSUPPORT_CREATE_SUCCESS";
export const INNOVATIONSUPPORT_CREATE_FAIL = "INNOVATIONSUPPORT_CREATE_FAIL";
